#include <windows.h>

namespace colors
{
	// Vordergrundfarben: 
	static const DWORD FG_BLACK(0);
	static const DWORD FG_BLUE(FOREGROUND_BLUE | FOREGROUND_INTENSITY);
	static const DWORD FG_BROWN(FOREGROUND_RED | FOREGROUND_GREEN);
	static const DWORD FG_DARKBLUE(FOREGROUND_BLUE);
	static const DWORD FG_DARKGREY(FOREGROUND_INTENSITY);
	static const DWORD FG_GREEN(FOREGROUND_GREEN);
	static const DWORD FG_GREY(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE);
	static const DWORD FG_LIGHTBLUE(FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	static const DWORD FG_LIGHTGREEN(FOREGROUND_GREEN | FOREGROUND_INTENSITY);
	static const DWORD FG_PINK(FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY);
	static const DWORD FG_RED(FOREGROUND_RED);
	static const DWORD FG_ROSE(FOREGROUND_RED | FOREGROUND_INTENSITY);
	static const DWORD FG_TURQUOISE(FOREGROUND_BLUE | FOREGROUND_GREEN);
	static const DWORD FG_VIOLET(FOREGROUND_RED | FOREGROUND_BLUE);
	static const DWORD FG_WHITE(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY);
	static const DWORD FG_YELLOW(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);

	// Hintergrundfarben: 
	static const DWORD BG_BLACK(0);
	static const DWORD BG_BLUE(BACKGROUND_BLUE | BACKGROUND_INTENSITY);
	static const DWORD BG_BROWN(BACKGROUND_RED | BACKGROUND_GREEN);
	static const DWORD BG_DARKBLUE(BACKGROUND_BLUE);
	static const DWORD BG_DARKGREY(BACKGROUND_INTENSITY);
	static const DWORD BG_GREEN(BACKGROUND_GREEN);
	static const DWORD BG_GREY(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE);
	static const DWORD BG_LIGHTBLUE(BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	static const DWORD BG_LIGHTGREEN(BACKGROUND_GREEN | BACKGROUND_INTENSITY);
	static const DWORD BG_PINK(BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY);
	static const DWORD BG_RED(BACKGROUND_RED);
	static const DWORD BG_ROSE(BACKGROUND_RED | BACKGROUND_INTENSITY);
	static const DWORD BG_TURQUOISE(BACKGROUND_BLUE | BACKGROUND_GREEN);
	static const DWORD BG_VIOLET(BACKGROUND_RED | BACKGROUND_BLUE);
	static const DWORD BG_WHITE(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY);
	static const DWORD BG_YELLOW(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY);
}